### PR TITLE
parametric: Add cpp-http server

### PR DESCRIPTION
**Pull request by dmehala**
## Motivation

Add cpp HTTP server for [the gRPC -> HTTP migration](https://docs.google.com/document/d/1qacYmyyIgMuAo8NxwbyH0paOf7f6bfe89QQUPPFygqA).

## Changes

- Add a new folder containing the new HTTP server implementation.
- Update parametric `conftest` to use the HTTP server instead of gRPC.

## Workflow

1. ⚠️ Create your PR as draft ⚠️
2. Work on you PR until the CI passes (if something not related to your task is failing, you can ignore it)
3. Mark it as ready for review
    * Test logic is modified? -> Get a review from RFC owner. We're working on refining the `codeowners` file quickly.
    * Framework is modified, or non obvious usage of it -> get a review from [R&P team](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X)

:rocket: Once your PR is reviewed, you can merge it!

🛟 [#apm-shared-testing](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X) 🛟

## Reviewer checklist

* [x] [Relevant label](https://github.com/DataDog/system-tests/blob/main/docs/CI/labels.md) (`run-parametric-scenario`, `run-profiling-scenario`...) are presents
* [ ] No system-tests internal is modified. Otherwise, I have the approval from [R&P team](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X)
* [ ] CI is green, or failing jobs are not related to this change (and you are 100% sure about this statement)
* [ ] A docker base image is modified?
    * [ ] the relevant `build-XXX-image` label is present
    * [ ] To R&P team: locally build and push the image to hub.docker.com 
* [ ] A scenario is added (or removed)?
    * [ ] Get a review from [R&P team](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X)
    * [ ] Once merged, add (or remove) it in system-test-dasboard nightly

### CODE REVIEW

**Review by robertomonteromiguel — CHANGES_REQUESTED** [review]
CI fails

**Review by robertomonteromiguel — APPROVED** [review]

**Comment by robertomonteromiguel** [comment]
is this PR ready for merge?

**Comment by dmehala** [comment]
I was waiting for a review from my team. With christmast and new year eve, it was possible apparently. I was planning to merge it today anyway, thank you for the wait @robertomonteromiguel

**Comment by dgoffredo** [comment]
From the [linked document][1]:

> Contributing to parametric tests with gRPC is unnecessarily difficult. HTTP and JSON are more familiar to APM library developers. PHP does not support gRPC [...]

I'm not familiar with the space, but I wonder if that quote can be reduced to "The PHP team did not want to provide a gRPC server."

Regardless, one way is better than two. Seeing that you got HTTP working, can we remove the gRPC server also?

[1]: https://docs.google.com/document/d/1qacYmyyIgMuAo8NxwbyH0paOf7f6bfe89QQUPPFygqA

**Pull request merged**
