### PR TITLE
Build labels

### PR DESCRIPTION
**Pull request by robertomonteromiguel**
## Description

By default we only execute default scenario on PRs
*Please include a short summary of the change*

## Workflow

1. ⚠️⚠️ Create your PR as draft (we're receiving lot of PR, it saves us lot of time) ⚠️⚠️
2. Follows the style guidelines of this project (See [how to easily lint the code](https://github.com/DataDog/system-tests/blob/main/docs/edit/lint.md))
3. Work on you PR until the CI passes (if something not related to your task is failing, you can ignore it)
4. Mark it as ready for review

Once your PR is reviewed, you can merge it ! :heart:

### CODE REVIEW

**Comment by robertomonteromiguel** [comment]
I have not modified generate-github-action-file.py, as it is going to disappear right?

**Comment by cbeauchesne** [comment]
yes, I think you can even remove it

**Comment by cbeauchesne** [comment]
I removed the label, and re-run the CI, only the default scenario ran :(

**Comment by robertomonteromiguel** [comment]
> I removed the label, and re-run the CI, only the default scenario ran :(

Upps, I forgot to add the "workflow dispatch". Now should work!

**Review by cbeauchesne — CHANGES_REQUESTED** [review]
Coiuld you write a quick doc how to use this ?  how as a PR author or reviewer I enable/disable entire workflow, and where to look for the CI process? And include a link in this doc at the bottm the PR template, explaining in a very quick sentence ehat's going on woth this label ?

**Comment by robertomonteromiguel** [comment]
> Coiuld you write a quick doc how to use this ? how as a PR author or reviewer I enable/disable entire workflow, and where to look for the CI process? And include a link in this doc at the bottm the PR template, explaining in a very quick sentence ehat's going on woth this label ?

https://datadoghq.atlassian.net/wiki/spaces/APMINT/pages/2866381467/CI+Workflow+Github+Actions

**Pull request merged**
