### PR TITLE
[python] remove INPLAT-220 skips from test cases

### PR DESCRIPTION
**Pull request by brettlangdon**
## Motivation

https://github.com/DataDog/dd-trace-py/pull/11464 has been merged fixing this bug. Tests should be enabled again.

## Workflow

1. ⚠️ Create your PR as draft ⚠️
2. Work on you PR until the CI passes (if something not related to your task is failing, you can ignore it)
3. Mark it as ready for review
    * Test logic is modified? -> Get a review from RFC owner. We're working on refining the `codeowners` file quickly.
    * Framework is modified, or non obvious usage of it -> get a review from [R&P team](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X)

:rocket: Once your PR is reviewed, you can merge it!

🛟 [#apm-shared-testing](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X) 🛟

## Reviewer checklist

* [ ] If PR title starts with `[<language>]`, double-check that only `<language>` is impacted by the change
* [ ] No system-tests internal is modified. Otherwise, I have the approval from [R&P team](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X)
* [ ] CI is green, or failing jobs are not related to this change (and you are 100% sure about this statement)
* [ ] A docker base image is modified?
    * [ ] the relevant `build-XXX-image` label is present
* [ ] A scenario is added (or removed)?
    * [ ] Get a review from [R&P team](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X)

### CODE REVIEW

**Comment by brettlangdon** [comment]
I think this first needs a release of `ddtrace` to PyPI fixing the issue first before the tests will pass.

**Review by emmettbutler — APPROVED** [review]

**Comment by brettlangdon** [comment]
These jobs are still failing. I need to dig into the logs to see if it is the same issue or not.

**Review by robertomonteromiguel — CHANGES_REQUESTED** [review]
I tested using prod and dev environment. In both cases is failing.
The dev environment is using this artifacts:
```agent: 1:7.59.0-1
datadog-apm-inject: 0.23.0-dev.b0d6e40.glci714805095.g7293f2e7
datadog-apm-library: 2.18.0.dev37+gbad0d272e```
is the library version ok? are we uploading the library artifact to staging?

**Comment by brettlangdon** [comment]
That dev artifact looks good to me, at least the version string looks correct.

I'll have to check the logs for dev.

But the fix is not yet released to "prod", but maybe we need to do some extra manual testing to verify too.

**Comment by robertomonteromiguel** [comment]
> That dev artifact looks good to me, at least the version string looks correct.
> 
> I'll have to check the logs for dev.
> 
> But the fix is not yet released to "prod", but maybe we need to do some extra manual testing to verify too.

Here you can see the logs for last execution I launched for dev: https://gitlab.ddbuild.io/DataDog/system-tests/-/jobs/716697641

If we achieve getting work for dev,  I can add a marker like "missing_feature tracer < xx.xx.xx"

**Comment by brettlangdon** [comment]
> > That dev artifact looks good to me, at least the version string looks correct.
> > I'll have to check the logs for dev.
> > But the fix is not yet released to "prod", but maybe we need to do some extra manual testing to verify too.
> 
> Here you can see the logs for last execution I launched for dev: [gitlab.ddbuild.io/DataDog/system-tests/-/jobs/716697641](https://gitlab.ddbuild.io/DataDog/system-tests/-/jobs/716697641)
> 
> If we achieve getting work for dev, I can add a marker like "missing_feature tracer < xx.xx.xx"

@robertomonteromiguel what determines which version to use for "dev", that commit is like 3 days old, so it doesn't have the most recent changes on `main` / including Emmett's fixes.

**Comment by robertomonteromiguel** [comment]
> > > That dev artifact looks good to me, at least the version string looks correct.
> > > I'll have to check the logs for dev.
> > > But the fix is not yet released to "prod", but maybe we need to do some extra manual testing to verify too.
> > 
> > 
> > Here you can see the logs for last execution I launched for dev: [gitlab.ddbuild.io/DataDog/system-tests/-/jobs/716697641](https://gitlab.ddbuild.io/DataDog/system-tests/-/jobs/716697641)
> > If we achieve getting work for dev, I can add a marker like "missing_feature tracer < xx.xx.xx"
> 
> @robertomonteromiguel what determines which version to use for "dev", that commit is like 3 days old, so it doesn't have the most recent changes on `main` / including Emmett's fixes.

To run the tests agains snapshot version of the tracer, you should run the jobs using the parameter "ONBOARDING_FILTER_ENV"

**Comment by robertomonteromiguel** [comment]
> > > > That dev artifact looks good to me, at least the version string looks correct.
> > > > I'll have to check the logs for dev.
> > > > But the fix is not yet released to "prod", but maybe we need to do some extra manual testing to verify too.
> > > 
> > > 
> > > Here you can see the logs for last execution I launched for dev: [gitlab.ddbuild.io/DataDog/system-tests/-/jobs/716697641](https://gitlab.ddbuild.io/DataDog/system-tests/-/jobs/716697641)
> > > If we achieve getting work for dev, I can add a marker like "missing_feature tracer < xx.xx.xx"
> > 
> > 
> > @robertomonteromiguel what determines which version to use for "dev", that commit is like 3 days old, so it doesn't have the most recent changes on `main` / including Emmett's fixes.
> 
> To run the tests agains snapshot version of the tracer, you should run the jobs using the parameter "ONBOARDING_FILTER_ENV"

I launched for dev and it's working:https://gitlab.ddbuild.io/DataDog/system-tests/-/pipelines?ref=brettlangdon%2Fremove.py.skips

Let me figure out how to skip for current prod artifact before merge the PR

**Comment by brettlangdon** [comment]
@robertomonteromiguel v2.17.1 is being released right now with these fixes, so afterwards `prod` should start to pass without any changes needed?

**Comment by brettlangdon** [comment]
2.17.1 is now released

**Pull request merged**
