### PR TITLE
[python]attempt to enable telemetry tests for python [INPLAT-36]

### PR DESCRIPTION
**Pull request by emmettbutler**
Adds smoke tests for auto-injection telemetry from dd-trace-py. Currently skipped as `bug` due to https://github.com/DataDog/dd-trace-py/pull/11101

## Reviewer checklist

* [ ] If PR title starts with `[<language>]`, double-check that only `<language>` is impacted by the change
* [ ] No system-tests internal is modified. Otherwise, I have the approval from [R&P team](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X)
* [ ] CI is green, or failing jobs are not related to this change (and you are 100% sure about this statement)
* [ ] A docker base image is modified?
    * [ ] the relevant `build-XXX-image` label is present
* [ ] A scenario is added (or removed)?
    * [ ] Get a review from [R&P team](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X)

### CODE REVIEW

**Review by cbeauchesne — COMMENTED** [review]
I think you need to define python weblogs in `utils/docker_ssi/docker_ssi_definitions.py`

cc @robertomonteromiguel

**Comment by robertomonteromiguel** [comment]
Yes, I think we can set this PR as draft, because we need to add the python scripts, docker files....
@iamluc is looking that too

**Comment by emmettbutler** [comment]
@robertomonteromiguel let me know if this looks right to you. I believe I've got it all working with the exception of the tests actually passing, since there's a known issue with Python wherein it doesn't send SSI telemetry (iirc).

**Review by robertomonteromiguel — CHANGES_REQUESTED** [review]
There is still one error on CI

**Pull request merged**
