### PR TITLE
Tests for url redaction

### PR DESCRIPTION
**Pull request by robertpi**

### CODE REVIEW

**Review by cbeauchesne — CHANGES_REQUESTED** [review]
could you just add `@rfc("...")` with the rfc link at the top of the class ?  :pray:

**Comment by simon-id** [comment]
@robertpi @cbeauchesne I added the rfc decorator as it looks like Robert is busy these days

**Review by cbeauchesne — COMMENTED** [review]
just wait for the CI before merging

**Comment by simon-id** [comment]
I think the test cases are wrong @robertpi when i try on regex101 it doesn't have the expected outcome

**Comment by cbeauchesne** [comment]
@simon-id I think they are not regex

**Comment by simon-id** [comment]
@robertpi https://regex101.com/r/LsLd9L/1

**Comment by robertpi** [comment]
> @robertpi https://regex101.com/r/LsLd9L/1

Yes, I misunderstood the standard regex when writing the test, corrected now.

**Pull request merged**
