### PR TITLE
Release versions for config consistency efforts

### PR DESCRIPTION
**Pull request by mhlidd**
## Motivation

Update Java manifest file to include updated config implementations from Config Consistency Work.

## Workflow

1. ⚠️ Create your PR as draft ⚠️
2. Work on you PR until the CI passes (if something not related to your task is failing, you can ignore it)
3. Mark it as ready for review
    * Test logic is modified? -> Get a review from RFC owner. We're working on refining the `codeowners` file quickly.
    * Framework is modified, or non obvious usage of it -> get a review from [R&P team](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X)

:rocket: Once your PR is reviewed, you can merge it!

🛟 [#apm-shared-testing](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X) 🛟

## Reviewer checklist

* [ ] If PR title starts with `[<language>]`, double-check that only `<language>` is impacted by the change
* [ ] No system-tests internal is modified. Otherwise, I have the approval from [R&P team](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X)
* [ ] CI is green, or failing jobs are not related to this change (and you are 100% sure about this statement)
* [ ] A docker base image is modified?
    * [ ] the relevant `build-XXX-image` label is present
* [ ] A scenario is added (or removed)?
    * [ ] Get a review from [R&P team](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X)

### CODE REVIEW

**Review by khanayan123 — APPROVED** [review]

**Review by mtoffl01 — APPROVED** [review]

**Review by smola — APPROVED** [review]

**Review by cbeauchesne — COMMENTED** [review]
Warning, test logic has been modified, you should not use a prefix in PR title in that situation, otherwise you may break system-tests, and other repo CI.

I've corrected the title and re-run the CI

**Review by cbeauchesne — APPROVED** [review]
Failure is not related

**Comment by mhlidd** [comment]
> Failure is not related

FYI `tests/test_config_consistency.py::Test_Config_HttpServerErrorStatuses_FeatureFlagCustom` is also failing on Golang, but a fix is on the way. https://dd.slack.com/archives/C02DW5ZH1EF/p1730737481291809

**Comment by cbeauchesne** [comment]
I've seen that :) you can safely merge this PR

**Pull request merged**
