### PR TITLE
remove java from missing

### PR DESCRIPTION
**Pull request by rtfpessoa**

### CODE REVIEW

**Comment by cbeauchesne** [comment]
Seems to have something failing on java : https://github.com/DataDog/system-tests/actions/runs/3105516650/jobs/5031260773#step:13:163

Though, the test may not be ok, as it says the agent "invented" some data. I'll have a look tomorrow

**Comment by cbeauchesne** [comment]
Well, I've tried to skip on test, but there are another test failing. @rtfpessoa, are you sure that the Java tracer fullfill the RFC?

**Comment by robertomonteromiguel** [comment]
**Exception: Agent proxy forwarded a message that was not sent by the library**

I guess this test will always be flaky due to t we store the library data and the agent data at different times and compare them (A "heartbeat" message may have been produced between the two moments.). 

But from the time the library data is saved (variable self.library_requests) until the agent data is saved (variable self.agent_requests) some seconds pass (see trace "Wait for agent's interface validation for 5 seconds"), meanwhile the application can continue producing "request_type: app-heartbeat" messages that will finally reach the agent (but will not be saved in library_requests because this "sava_data" process has already been executed before).

_See lines:_ 

https://github.com/DataDog/system-tests/blob/8e5071f450982d17c3a12c6525916b09a923ff4c/tests/test_telemetry.py#L137

https://github.com/DataDog/system-tests/blob/8e5071f450982d17c3a12c6525916b09a923ff4c/tests/test_telemetry.py#L140

https://github.com/DataDog/system-tests/blob/8e5071f450982d17c3a12c6525916b09a923ff4c/tests/test_telemetry.py#L143

_Log file example:_

`19:54:56.722 DEBUG    Load test validations
19:54:56.755 DEBUG    _FinalValidation('Test that all telemetry requests sent by library are forwarded correctly by the agent') added in agent interface[4]
....
....
19:56:30.149 DEBUG    LIBRARY save_data (1, '6bc2e507-065b-4b41-b5cb-a8ea4a740eff')
19:56:30.149 DEBUG    LIBRARY save_data (2, '6bc2e507-065b-4b41-b5cb-a8ea4a740eff')
19:56:30.149 DEBUG    LIBRARY save_data (3, '6bc2e507-065b-4b41-b5cb-a8ea4a740eff')
19:56:30.149 DEBUG    LIBRARY save_data (4, '6bc2e507-065b-4b41-b5cb-a8ea4a740eff')
19:56:30.149 DEBUG    Found span with rid=KOCZFBVMMCNQKAIVRUIQAHXBUBCWXMNZPHSX: span_id=9188367073101123762
19:56:30.150 DEBUG    Found span with rid=NUFKRFPEDSYPAEYTSTNUBZCJTWYOKCRAVSCG: span_id=658878256597086901
19:56:30.151 DEBUG    Found span with rid=ZGWODTUQYUMYLRZWQNKLWNTGUSMMAHCCPIIY: span_id=6873246061293922454
19:56:30.151 DEBUG    Found span with rid=XWPMUXSRMZWWNFBVPIDZYPBGCTGWPGUGTFWE: span_id=4048536701260995104
19:56:30.152 DEBUG    Found span with rid=HOCNHUPCMGYEZDXDBYMQPQGXSUAUJRNLWPCQ: span_id=5903111693141568137
19:56:30.153 DEBUG    Found span with rid=FBMDAYUPCILSQKZPEGUEQXNEXOFJYSLVWSAB: span_id=6770972626152883212
19:56:30.154 DEBUG    Found span with rid=RCQJATHXPQZCZQKSLNKWSZKMSNXBKKMKIJRJ: span_id=8491734990931434425
19:56:30.154 DEBUG    Found span with rid=COUVEODXHLORCUCNHNHONYYBWQGQHAFORFZC: span_id=7872299853453740944
19:56:30.155 DEBUG    Found a trace for Verify the /trace/ognl endpoint is setup
19:56:30.156 DEBUG    Found a trace for Verify the /rasp/sqli endpoint is setup
........
........
19:56:32.083 INFO     Wait for agent's interface validation for 5 seconds
19:56:37.114 DEBUG    AGENT save_data (1, '6bc2e507-065b-4b41-b5cb-a8ea4a740eff')
19:56:37.114 DEBUG    AGENT save_data (2, '6bc2e507-065b-4b41-b5cb-a8ea4a740eff')
19:56:37.114 DEBUG    AGENT save_data (3, '6bc2e507-065b-4b41-b5cb-a8ea4a740eff')
19:56:37.114 DEBUG    AGENT save_data (4, '6bc2e507-065b-4b41-b5cb-a8ea4a740eff')
19:56:37.114 DEBUG    AGENT save_data (5, '6bc2e507-065b-4b41-b5cb-a8ea4a740eff')
19:56:37.114 DEBUG    START FINAL VALIDATION check_data_consistency
19:56:37.115 ERROR    [94mTest that all telemetry requests sent by library are forwarded correctly by the agent[0m not validated: Exception: Agent proxy forwarded a message that was not sent by the library: logs/interfaces/agent/029__api_v2_apmtelemetry.json
`

What do you think? @cbeauchesne @rtfpessoa

**Comment by cbeauchesne** [comment]
I've updated your branch, there were an issue fixed by #519

**Comment by rtfpessoa** [comment]
@cbeauchesne @ValentinZakharov What are we missing here?

**Review by cbeauchesne — APPROVED** [review]

**Pull request merged**
