### PR TITLE
fix flaking nodejs sqs test

### PR DESCRIPTION
**Pull request by wconti27**
## Motivation

Fix flaking test

## Workflow

1. ⚠️ Create your PR as draft ⚠️
2. Work on you PR until the CI passes (if something not related to your task is failing, you can ignore it)
3. Mark it as ready for review
    * Test logic is modified? -> Get a review from RFC owner. We're working on refining the `codeowners` file quickly.
    * Framework is modified, or non obvious usage of it -> get a review from [R&P team](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X)

:rocket: Once your PR is reviewed, you can merge it!

🛟 [#apm-shared-testing](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X) 🛟

## Reviewer checklist

* [ ] [Relevant label](https://github.com/DataDog/system-tests/blob/main/docs/CI/labels.md) (`run-parametric-scenario`, `run-profiling-scenario`...) are presents
* [ ] No system-tests internal is modified. Otherwise, I have the approval from [R&P team](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X)
* [ ] CI is green, or failing jobs are not related to this change (and you are 100% sure about this statement)
* [ ] A docker base image is modified?
    * [ ] the relevant `build-XXX-image` label is present
    * [ ] To R&P team: locally build and push the image to hub.docker.com 
* [ ] A scenario is added (or removed)?
    * [ ] Get a review from [R&P team](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X)
    * [ ] Once merged, add (or remove) it in system-test-dasboard nightly

### CODE REVIEW

**Comment by wconti27** [comment]
> I removed the `build-buddies` tag : as long as we don't need to modify buddies them, we must not rebuild them, to be sure what we fixed is actually on the test, and is compatible with existing buddies images

@cbeauchesne I was rebuilding buddies to include the newest release for the `dd-trace-py` tracer v2.6.1. This release enables propagation for AWS SQS, which is required for this flaky test case (I want to switch to using the python buddy as the base for the test, and need this updated buddy image).

**Review by robertomonteromiguel — CHANGES_REQUESTED** [review]
There are failing tests on the CI

**Comment by cbeauchesne** [comment]
> I was rebuilding buddies to include the newest release for the dd-trace-py tracer v2.6.1. This release enables propagation for AWS SQS, which is required for this flaky test case (I want to switch to using the python buddy as the base for the test, and need this updated buddy image).

my bad 😊

**Comment by wconti27** [comment]
> There are failing tests on the CI

The failing tests were due to the buddy images not being built, which means an old release of `dd-trace-py` was used in the buddy, resulting in test failures since it does not include the new release code for context propagation. This is expected, and tests are passing now that the buddies are being built again

**Review by cbeauchesne — APPROVED** [review]

**Review by robertomonteromiguel — APPROVED** [review]

**Pull request merged**
