### PR TITLE
Sleep mode for scenarios

### PR DESCRIPTION
**Pull request by robertomonteromiguel**
## Description
Enable sleep mode for different scenarios

## Workflow

1. ⚠️⚠️ Create your PR as draft
2. Follow the style guidelines of this project (See [how to easily lint the code](https://github.com/DataDog/system-tests/blob/main/docs/edit/lint.md))
3. Work on you PR until the CI passes (if something not related to your task is failing, you can ignore it)
4. Mark it as ready for review

Once your PR is reviewed, you can merge it! :heart:

## Reviewer checklist

* [ ] Check what scenarios are modified. If needed, add the relevant label (`run-parametric-scenario`, `run-profiling-scenario`...). If this PR modifies any system-tests internal, then add the `run-all-scenarios` label ([more info](https://github.com/DataDog/system-tests/blob/main/docs/CI/labels.md)). 
* [ ] CI is green
   * [ ] If not, failing jobs are not related to this change (and you are 100% sure about this statement)
* [ ] if any of `build-some-image` label is present
  1. is the image labl have been updated ? 
  2. just before merging, locally build and push the image to hub.docker.com
* [ ] if a scenario is added (or removed), add (or remove) it in system-test-dasboard nightly

### CODE REVIEW

**Review by cbeauchesne — CHANGES_REQUESTED** [review]
By which wizardry it actually sleeps ? 

Also, could you remove the `sleep` scenario in `_scenarios.py` ?

**Comment by cbeauchesne** [comment]
Ah, ok !

I think we could to this a little bit better : in `pytest_collection_finish`, commented lines are from me : 

```
    if session.config.option.collectonly:
        return
    
    if session.config.option.sleep:  # on this mode, we simply sleep, not running any test or setup
        try:
            logger.terminal("Sleep mode activated. Press Ctrl+C to exit")
            while True:  # inifinite sleep
                 sleep(1):   # arbitrary amount 
        except KeyboardInterrupt:   # catching ctrl+C
             pass
        finally:   # in case of other error
              pytest.exit(0). # exit in sucess
```        

And then, we can remove the sleep scenario :)

**Review by cbeauchesne — CHANGES_REQUESTED** [review]
Again a small leftover in _scneario.py to remove : the sleep scenario instance.

**Comment by robertomonteromiguel** [comment]
> Again a small leftover in _scneario.py to remove : the sleep scenario instance.

Uppss! Done!

**Review by cbeauchesne — APPROVED** [review]
You should communicate this on `apm-shared-testing` 🎉

**Pull request merged**
