### PR TITLE
[ruby] Remove/update outdated weblogs and clean rack config.ru

### PR DESCRIPTION
**Pull request by vpellan**
## Changes

- Refactored/cleaned `config.ru` from rack weblog
- Removed outdated Rails weblog (Rails 3, 4.0 and 4.1)
- Replaced Ruby 2.3 by Ruby 2.5 for Rails 4.2 weblog
- Added back Rails 4.2 in `compute-workflow-parameters`

## Workflow

1. ⚠️ Create your PR as draft ⚠️
2. Work on you PR until the CI passes (if something not related to your task is failing, you can ignore it)
3. Mark it as ready for review
    * Test logic is modified? -> Get a review from RFC owner. We're working on refining the `codeowners` file quickly.
    * Framework is modified, or non obvious usage of it -> get a review from [R&P team](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X)

:rocket: Once your PR is reviewed, you can merge it!

🛟 [#apm-shared-testing](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X) 🛟

## Reviewer checklist

* [ ] If PR title starts with `[<language>]`, double-check that only `<language>` is impacted by the change
* [ ] No system-tests internal is modified. Otherwise, I have the approval from [R&P team](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X)
* [ ] CI is green, or failing jobs are not related to this change (and you are 100% sure about this statement)
* [ ] A docker base image is modified?
    * [ ] the relevant `build-XXX-image` label is present
* [ ] A scenario is added (or removed)?
    * [ ] Get a review from [R&P team](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X)

### CODE REVIEW

**Review by cbeauchesne — CHANGES_REQUESTED** [review]
CI is failing : https://github.com/DataDog/system-tests/actions/runs/11109895081/job/30866393867?pr=3142#step:34:54

**Comment by vpellan** [comment]
> CI is failing : [DataDog/system-tests/actions/runs/11109895081/job/30866393867?pr=3142#step:34:54](https://github.com/DataDog/system-tests/actions/runs/11109895081/job/30866393867?pr=3142#step:34:54)

Should be fixed with latest commit, thanks !

**Comment by vpellan** [comment]
Updated title and PR description to reflect changes on Rails 4.2 weblog

**Review by Strech — APPROVED** [review]
Love to see more 🟥 🚢

**Review by y9v — APPROVED** [review]

**Pull request merged**
