### PR TITLE
M1 requires a dedicated image for .NET

### PR DESCRIPTION
**Pull request by cbeauchesne**
## Description

See title

## Check list

Your PR is not ready to be reviewed? Please save it as a draft :pray:

- [ ] Follows the style guidelines of this project (See [how to easily lint the code](https://github.com/DataDog/system-tests/blob/main/docs/edit/lint.md))
- [ ] CI is passing
- [ ] There is at least one approval from code owners

Yes to all? Feel free to merge it whenever you want :heart:

### CODE REVIEW

**Comment by mehulsonowal** [comment]
Dotnet is failing tests: [stdout.log](https://github.com/DataDog/system-tests/files/9902011/stdout.log)

**Comment by cbeauchesne** [comment]
See https://github.com/DataDog/system-tests/commit/87f0a68934cfc20a3a68f9890930f14b8ae775e6

**Comment by cbeauchesne** [comment]
@mehulsonowal could you give it another try please ?

**Comment by mehulsonowal** [comment]
@cbeauchesne adding this environment variable makes all tests pass for me: https://github.com/Azure/azure-functions-core-tools/issues/2901#issuecomment-1257037711

**Pull request merged**
