### PR TITLE
update telemetry language features

### PR DESCRIPTION
**Pull request by rtfpessoa**

### CODE REVIEW

**Comment by cbeauchesne** [comment]
@rtfpessoa there are issue in the CI on the activated test, no ?

**Comment by cbeauchesne** [comment]
@Kyle-Verhoog do you know what happened here ? https://github.com/DataDog/system-tests/actions/runs/3089788748/jobs/4997809005

@rtfpessoa you can ignore this failure

**Review by cbeauchesne — APPROVED** [review]

**Comment by Kyle-Verhoog** [comment]
> @Kyle-Verhoog do you know what happened here ? https://github.com/DataDog/system-tests/actions/runs/3089788748/jobs/4997809005

@ZStriker19 looks like `test_single_rule_always_keep_span_sampling_sss011` is a little flaky, should we expand the range a bit?

**Comment by ZStriker19** [comment]
Yeah I'll expand it

**Comment by ZStriker19** [comment]
https://github.com/DataDog/system-tests/pull/496

**Pull request merged**
