### PR TITLE
Parametric: add tests for headers precedence with conflicting context

### PR DESCRIPTION
**Pull request by ZStriker19**
## Description

When a tracer receives headers for multiple propagation styles that is supports, it should use the precedence of the styles to select the primary context, then if other contexts are extracted but do not match, the tracer should generate the  the proper span links and add them to the span.

## Workflow

1. ⚠️⚠️ Create your PR as draft
2. Follow the style guidelines of this project (See [how to easily lint the code](https://github.com/DataDog/system-tests/blob/main/docs/edit/lint.md))
3. Work on you PR until the CI passes (if something not related to your task is failing, you can ignore it)
4. Mark it as ready for review

Once your PR is reviewed, you can merge it! :heart:

## Reviewer checklist

* [ ] Check what scenarios are modified. If needed, add the relevant label (`run-parametric-scenario`, `run-profiling-scenario`...). If this PR modifies any system-tests internal, then add the `run-all-scenarios` label ([more info](https://github.com/DataDog/system-tests/blob/main/docs/CI/labels.md)). 
* [ ] CI is green
   * [ ] If not, failing jobs are not related to this change (and you are 100% sure about this statement)
* [ ] if any of `build-some-image` label is present
  1. is the image labl have been updated ? 
  2. just before merging, locally build and push the image to hub.docker.com
* [ ] if a scenario is added (or removed), add (or remove) it in system-test-dasboard nightly

### CODE REVIEW

**Comment by ZStriker19** [comment]
I don't think all of the other tracers should be failing on this by not having `span_links` on the span. Is there something enabled for python/python_http that hits a newer testagent version  or endpoint?

**Comment by ZStriker19** [comment]
This feature _should_ be functional on all tracers...

**Review by robertomonteromiguel — CHANGES_REQUESTED** [review]
There are tests failures in the CI build

**Comment by ZStriker19** [comment]
@robertomonteromiguel I'm having trouble seeing the error that's occurring in PHP, now that I'm skipping the test for the other libraries, and how it's related to the changes I've made. Any insight?

**Review by cbeauchesne — APPROVED** [review]

**Review by robertomonteromiguel — APPROVED** [review]

**Pull request merged**
