### PR TITLE
enable 128-bit trace id tests for node

### PR DESCRIPTION
**Pull request by rochdev**
## Description

Enable 128-bit trace ID tests for Node.

Related: https://github.com/DataDog/dd-trace-js/pull/2944

## Workflow

1. ⚠️⚠️ Create your PR as draft (we're receiving lot of PR, it saves us lot of time) ⚠️⚠️
2. Follows the style guidelines of this project (See [how to easily lint the code](https://github.com/DataDog/system-tests/blob/main/docs/edit/lint.md))
3. Work on you PR until the CI passes (if something not related to your task is failing, you can ignore it)
4. Mark it as ready for review

> **_NOTE:_**  By default in PR only default scenario tests will be launched. Please refer to the [documentation](https://datadoghq.atlassian.net/wiki/spaces/APMINT/pages/2866381467/CI+Workflow+Github+Actions) to run all scenarios in your PR if needed.

Once your PR is reviewed, you can merge it ! :heart:

### CODE REVIEW

**Comment by rochdev** [comment]
This is now ready for review as all tests pass locally and we'd like to be able to also run them in CI before merging/releasing the functionality.

**Comment by cbeauchesne** [comment]
> This is now ready for review as all tests pass locally and we'd like to be able to also run them in CI before merging/releasing the functionality.

Hi Roch,

Do you mean that you want to merge the PR in system test before yours ? (if yes, it means that it'll break your CI until you have merged yours)

**Comment by rochdev** [comment]
We're actually close to releasing the feature, so as long as this is approved we should be able to merge within a couple of days.

**Comment by rochdev** [comment]
@cbeauchesne The feature was now released in the latest version of dd-trace-js, so this can now also be merged.

**Review by cbeauchesne — APPROVED** [review]

**Pull request merged**
