### PR TITLE
feat(asm): honor DD_APPSEC_WAF_TIMEOUT

### PR DESCRIPTION
**Pull request by gnufede**

### CODE REVIEW

**Comment by cbeauchesne** [comment]
I'm a bit worried, did you validate with all appsec tracer owners the behavior of tracers when the value is 0 ?

**Comment by gnufede** [comment]
> I'm a bit worried, did you validate with all appsec tracer owners the behavior of tracers when the value is 0 ?

I have not, but I expect them all to behave properly. We should clarify it.

**Comment by cbeauchesne** [comment]
Asked on slack

**Comment by cbeauchesne** [comment]
Answer from slack : 0 is not supported, at least on .NET.

Except if I missed something, can I close this PR ?

**Comment by gnufede** [comment]
> Answer from slack : 0 is not supported, at least on .NET.
> 
> Except if I missed something, can I close this PR ?

How do we solve it for languages where 1 is not low enough?

Should we test with 1 or 0 depending on the language?

**Comment by gnufede** [comment]
We'll find a better way to make it work for all languages

**Pull request closed without merging**
