### PR TITLE
test debian 12

### PR DESCRIPTION
**Pull request by emmettbutler**
This pull request adds Debian 12 amd/arm to the list of operating systems tested with auto-instrumentation.

## Reviewer checklist

* [ ] If PR title starts with `[<language>]`, double-check that only `<language>` is impacted by the change
* [ ] No system-tests internal is modified. Otherwise, I have the approval from [R&P team](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X)
* [ ] CI is green, or failing jobs are not related to this change (and you are 100% sure about this statement)
* [ ] A docker base image is modified?
    * [ ] the relevant `build-XXX-image` label is present
* [ ] A scenario is added (or removed)?
    * [ ] Get a review from [R&P team](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X)

### CODE REVIEW

**Review by robertomonteromiguel — CHANGES_REQUESTED** [review]
You added the debian vm as not default vm, it is not going to execute on "extra vms" job.
Running other jobs I see this error:
06:37:03.584 INFO         	* creating EC2 Instance: InvalidParameterValue: The t2.medium instance type does not support an AMI with a boot mode of UEFI. Only instance types built on the Nitro System support UEFI. Specify an instance type that supports UEFI, and try again. 
The arm vms should be of type "t4g.small"

**Review by robertomonteromiguel — CHANGES_REQUESTED** [review]
I pushed a commit in your branch, because you were using a wrong username. Now the username is ok, but the tests are failing for Debian machines in some cases. For example, for dotnet I can see this error:
`Diagnostics:
  command:remote:Command (-Debian_12_amd64-dotnet):
    error: Process exited with status 100: running "sudo apt-get install -y dotnet-sdk-6.0\nsudo apt-get install -y dotnet-runtime-6.0\n":`

**Comment by emmettbutler** [comment]
@robertomonteromiguel I think this is in a better state now. I can't find any actionable error messages.

**Review by robertomonteromiguel — COMMENTED** [review]
I updated your branch from the main branch.
I fixed the jdk installation. 
It should work. I launched the full pipeline build, if the tests pass you can merge this PR.
Check the last pipeline execution: https://gitlab.ddbuild.io/DataDog/system-tests/-/pipelines/45703567

**Review by robertomonteromiguel — APPROVED** [review]

**Pull request merged**
