### PR TITLE
Fixes decision maker tag values for remote user rules and dynamic rules

### PR DESCRIPTION
**Pull request by yuanyuanzhao3**
This is to avoid a conflict with the duplicate value `-10` used by data jobs.

The Go tracer change is also being made and will be released in `1.63.1`.
## Workflow

1. ⚠️ Create your PR as draft ⚠️
2. Work on you PR until the CI passes (if something not related to your task is failing, you can ignore it)
3. Mark it as ready for review
    * Test logic is modified? -> Get a review from RFC owner. We're working on refining the `codeowners` file quickly.
    * Framework is modified, or non obvious usage of it -> get a review from [R&P team](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X)

:rocket: Once your PR is reviewed, you can merge it!

🛟 [#apm-shared-testing](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X) 🛟

## Reviewer checklist

* [ ] [Relevant label](https://github.com/DataDog/system-tests/blob/main/docs/CI/labels.md) (`run-parametric-scenario`, `run-profiling-scenario`...) are presents
* [ ] If PR title starts with `[<language>]`, double-check that only `<language>` is impacted by the change
* [ ] No system-tests internal is modified. Otherwise, I have the approval from [R&P team](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X)
* [ ] CI is green, or failing jobs are not related to this change (and you are 100% sure about this statement)
* [ ] A docker base image is modified?
    * [ ] the relevant `build-XXX-image` label is present
* [ ] A scenario is added (or removed)?
    * [ ] Get a review from [R&P team](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X)

### CODE REVIEW

**Comment by robertomonteromiguel** [comment]
There is a failure on parametric and go related with change.
I move this PR to draft

**Review by cbeauchesne — DISMISSED** [review]
CI fails on golang? maybe you're waiting for a PR to be merged on dd-trace-go ?

**Comment by yuanyuanzhao3** [comment]
> CI fails on golang? maybe you're waiting for a PR to be merged on dd-trace-go ?

Yes, there is a corresponding dd-trace-go change. But that can't be made easily for the chicken-n-egg problem (see [this discussion](https://dd.slack.com/archives/C025TJ4RZ8X/p1714158701032179).

**Review by darccio — APPROVED** [review]

**Comment by yuanyuanzhao3** [comment]
> > CI fails on golang? maybe you're waiting for a PR to be merged on dd-trace-go ?
> 
> Yes, there is a corresponding dd-trace-go change. But that can't be made easily for the chicken-n-egg problem (see [this discussion](https://dd.slack.com/archives/C025TJ4RZ8X/p1714158701032179)).

Pending dd-trace-go change was merged. All tests passed now.

**Review by cbeauchesne — APPROVED** [review]

**Pull request merged**
