### PR TITLE
Add dynamic config capabilities, custom tags

### PR DESCRIPTION
**Pull request by Kyle-Verhoog**
## Description

Add shared tests for the extension of the remote configuration of tracer library settings functionality. The extension includes:

- Libraries report which features they support via an RC feature called "capabilities".
- Libraries can configure custom tags (equivalent of the `DD_TAGS` feature) via Remote Config.

https://datadoghq.atlassian.net/browse/APMON-314

## Workflow

1. ⚠️⚠️ Create your PR as draft
2. Follow the style guidelines of this project (See [how to easily lint the code](https://github.com/DataDog/system-tests/blob/main/docs/edit/lint.md))
3. Work on you PR until the CI passes (if something not related to your task is failing, you can ignore it)
4. Mark it as ready for review

Once your PR is reviewed, you can merge it! :heart:

## Reviewer checklist

* [x] Check what scenarios are modified. If needed, add the relevant label (`run-parametric-scenario`, `run-profiling-scenario`...). If this PR modifies any system-tests internal, then add the `run-all-scenarios` label ([more info](https://github.com/DataDog/system-tests/blob/main/docs/CI/labels.md)). 
* [ ] CI is green
   * [ ] If not, failing jobs are not related to this change (and you are 100% sure about this statement)
* [ ] if any of `build-some-image` label is present
  1. is the image labl have been updated ? 
  2. just before merging, locally build and push the image to hub.docker.com
* [ ] if a scenario is added (or removed), add (or remove) it in system-test-dasboard nightly

### CODE REVIEW

**Comment by ahmed-mez** [comment]
@Kyle-Verhoog lmk if the last commit makes sense!

**Review by ahmed-mez — APPROVED** [review]

**Review by cbeauchesne — CHANGES_REQUESTED** [review]
CI is failing

**Comment by Kyle-Verhoog** [comment]
@cbeauchesne looks like the tests failing are unrelated. Rerunning them.

**Comment by cbeauchesne** [comment]
ouch, not a good news (I admit I didn't looked , shame on me 😅 )

**Comment by ahmed-mez** [comment]
I confirm that the failure in parametric Go is unrelated and will be fixed soon (cc @katiehockman).

**Review by cbeauchesne — APPROVED** [review]

**Pull request merged**
