### PR TITLE
Enhance partial flushing tests in prep for enabling by default

### PR DESCRIPTION
**Pull request by ajgajg1134**
## Motivation
To prepare for enabling partial flushing by default we want to build additional confidence in the correctness of the implementation. This adds a few small checks to verify different languages are properly attaching expected trace level tags on partial chunks. This change even caught a bug in the nodejs tracer where it doesn't send the upper 64 bits of the trace ID on a partial chunk

## Workflow

1. ⚠️ Create your PR as draft ⚠️
2. Work on you PR until the CI passes (if something not related to your task is failing, you can ignore it)
3. Mark it as ready for review
    * Test logic is modified? -> Get a review from RFC owner. We're working on refining the `codeowners` file quickly.
    * Framework is modified, or non obvious usage of it -> get a review from [R&P team](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X)

:rocket: Once your PR is reviewed, you can merge it!

🛟 [#apm-shared-testing](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X) 🛟

## Reviewer checklist

* [x] If PR title starts with `[<language>]`, double-check that only `<language>` is impacted by the change
* [ ] No system-tests internal is modified. Otherwise, I have the approval from [R&P team](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X)
* [ ] CI is green, or failing jobs are not related to this change (and you are 100% sure about this statement)
* [ ] A docker base image is modified?
    * [ ] the relevant `build-XXX-image` label is present
* [ ] A scenario is added (or removed)?
    * [ ] Get a review from [R&P team](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X)

### CODE REVIEW

**Review by robertomonteromiguel — APPROVED** [review]

**Comment by ajgajg1134** [comment]
It appears the 3 failing checks here are unrelated Ruby failures

**Comment by dmehala** [comment]
@ajgajg1134 naive question, is partial flushing spec'd somewhere?

**Comment by ajgajg1134** [comment]
> @ajgajg1134 naive question unrelated to this PR, is partial flushing spec'd somewhere?

This is a totally fair question, and unfortunately there is not an official spec. I've been assembling details / documents and we have a few internal resources here:
* https://datadoghq.atlassian.net/wiki/spaces/APMINT/pages/2564227120/Trace+Agent+Partial+Flushing
* https://docs.google.com/document/d/1RT6lp10M0a0rp0cGQhgN_fRGaxGgVk1LZjjJfGRM1BQ/edit?tab=t.0
* https://docs.google.com/document/d/1ivPw_6croUQsbYAsdTMUv8zwPZOPnPPzFBUYUDvelmg/edit?tab=t.0

**Comment by ajgajg1134** [comment]
Current failures are still just flaking ruby tests in parametric tests it seems? @mabdinur Do the latest changes here for manifest files match you expect? I'm not 100% sure I covered what you meant :P

**Review by cbeauchesne — APPROVED** [review]

**Review by mabdinur — APPROVED** [review]

**Pull request merged**
