### PR TITLE
Remove missing_feature for PHP in 128 bit trace id tests

### PR DESCRIPTION
**Pull request by bwoebi**
I have no idea why these tests are disabled, but they work.

### CODE REVIEW

**Review by cbeauchesne — CHANGES_REQUESTED** [review]
CI is failing on activated tests

**Review by cbeauchesne — CHANGES_REQUESTED** [review]
Failing on `test_w3c_128_bit_propagation_tid_in_parent`

**Comment by bwoebi** [comment]
I see, the test is broken, there's no meta on the child, because it's empty.

**Comment by bwoebi** [comment]
@cbeauchesne Now it's actually green :-)

**Review by cbeauchesne — APPROVED** [review]

**Pull request merged**
