### PR TITLE
Add NoSQL injection iast test for mongodb in nodejs

### PR DESCRIPTION
**Pull request by uurien**
## Description

Adds the system test to validate that NoSQL injection detection in iast is working as expected.

## Workflow

1. ⚠️⚠️ Create your PR as draft
2. Follow the style guidelines of this project (See [how to easily lint the code](https://github.com/DataDog/system-tests/blob/main/docs/edit/lint.md))
3. Work on you PR until the CI passes (if something not related to your task is failing, you can ignore it)
4. Mark it as ready for review

Once your PR is reviewed, you can merge it! :heart:

## Reviewer checklist

* [ ] Check what scenarios are modified. If needed, add the relevant label (`run-parametric-scenario`, `run-profiling-scenario`...). If this PR modifies any system-tests internal, then add the `run-all-scenarios` label ([more info](https://github.com/DataDog/system-tests/blob/main/docs/CI/labels.md)). 
* [ ] CI is green
   * [ ] If not, failing jobs are not related to this change (and you are 100% sure about this statement)
* [ ] if any of `build-some-image` label is present
  1. is the image labl have been updated ? 
  2. just before merging, locally build and push the image to hub.docker.com
* [ ] if a scenario is added (or removed), add (or remove) it in system-test-dasboard nightly

### CODE REVIEW

**Review by cbeauchesne — COMMENTED** [review]
Also, in `.github/workflows/ci.yml`, line 297, you must replace `needs.scenarios.outputs.run_all == 'true'` by `needs.scenarios.outputs.run_appsec == 'true'`

**Review by cbeauchesne — CHANGES_REQUESTED** [review]
INTEGRATIONS scenario is brokken, looks like nothing is reported anymore : https://github.com/DataDog/system-tests/actions/runs/6457939241/job/17530667674?pr=1643#step:17:86

Are you sure about changes on weblog ?

**Comment by uurien** [comment]
> INTEGRATIONS scenario is brokken, looks like nothing is reported anymore : https://github.com/DataDog/system-tests/actions/runs/6457939241/job/17530667674?pr=1643#step:17:86
> 
> Are you sure about changes on weblog ?

I should review it now. Because the CI was green before the merge from main.

**Review by cbeauchesne — APPROVED** [review]
Well probably some flakiness to address later on

**Pull request merged**
