### PR TITLE
ASM - Add endpoint for open redirect

### PR DESCRIPTION
**Pull request by Taiki-San**
## Description

Add a new endpoint to Java test app for Open Redirect

## Workflow

1. ⚠️⚠️ Create your PR as draft (we're receiving lot of PR, it saves us lot of time) ⚠️⚠️
2. Follows the style guidelines of this project (See [how to easily lint the code](https://github.com/DataDog/system-tests/blob/main/docs/edit/lint.md))
3. Work on you PR until the CI passes (if something not related to your task is failing, you can ignore it)
4. Mark it as ready for review

Once your PR is reviewed, you can merge it ! :heart:

### CODE REVIEW

**Review by cbeauchesne — COMMENTED** [review]
Could explain what would be the testing purpose/context of this endpoint ?

**Comment by Taiki-San** [comment]
@cbeauchesne The endpoint redirect the user to a URL, either arbitrary or a default one. The goal is to simulate an endpoint vulnerable to the Open Redirect vulnerability.
I haven't added a test because we're still evaluating the vulnerability and aren't sure about the coverage we want to bring. Since I used the system test app to prototype it, I figured it may be worth upstreaming, although I'm fine maintaining a fork if you think otherwise.

**Review by cbeauchesne — CHANGES_REQUESTED** [review]
nope, that's ok. Could you just change the endpoint name to something explicit, like `/experimental/redirect` ?

**Comment by Taiki-San** [comment]
Done!

**Review by cbeauchesne — APPROVED** [review]

**Pull request merged**
