### PR TITLE
test ubuntu 18 ARM

### PR DESCRIPTION
**Pull request by emmettbutler**
This pull request adds Ubuntu 18 arm64 to the list of operating systems tested with auto-instrumentation.

## Reviewer checklist

* [ ] If PR title starts with `[<language>]`, double-check that only `<language>` is impacted by the change
* [ ] No system-tests internal is modified. Otherwise, I have the approval from [R&P team](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X)
* [ ] CI is green, or failing jobs are not related to this change (and you are 100% sure about this statement)
* [ ] A docker base image is modified?
    * [ ] the relevant `build-XXX-image` label is present
* [ ] A scenario is added (or removed)?
    * [ ] Get a review from [R&P team](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X)

### CODE REVIEW

**Review by robertomonteromiguel — CHANGES_REQUESTED** [review]
You added the ubuntu 18 arm vm as not default vm, it is not going to execute on "extra vms" job.
Running other jobs I see this error:
`06:37:03.584 INFO         	* creating EC2 Instance: InvalidParameterValue: The t2.medium instance type does not support an AMI with a boot mode of UEFI. Only instance types built on the Nitro System support UEFI. Specify an instance type that supports UEFI, and try again.
`
The arm vms should be of type "t4g.small"

**Comment by emmettbutler** [comment]
@robertomonteromiguel 

> You added the ubuntu 18 arm vm as not default vm, it is not going to execute on "extra vms" job.

I don't see the difference between this change and how I approached the Fedora change. What do I need to change on this PR?

**Review by robertomonteromiguel — CHANGES_REQUESTED** [review]
You need to choose another AMI, because this one requires a subscription:

`06:41:04.772 INFO       aws:ec2:Instance (Ubuntu_18_arm64):
06:41:04.772 INFO         error: 1 error occurred:
06:41:04.773 INFO         	* creating EC2 Instance: OptInRequired: In order to use this AWS Marketplace product you need to accept terms and subscribe. To do so please visit https://aws.amazon.com/marketplace/pp?sku=c32m5ohwwfzz4h6g2anowwufo
06:41:04.773 INFO         	status code: 401, request id: 6f963b00-0c57-45a9-bb3e-21f185c654bf`

**Review by robertomonteromiguel — CHANGES_REQUESTED** [review]
`* creating EC2 Instance: OptInRequired: In order to use this AWS Marketplace product you need to accept terms and subscribe. To do so please visit https://aws.amazon.com/marketplace/pp?sku=13816qtz8odg70eycm8235rw5
20:13:07.847 INFO         	status code: 401, request id: 48aeabe9-e07a-40af-ab40-021e952558f4`

**Pull request closed without merging**
