### PR TITLE
Lib injection test for Ruby 

### PR DESCRIPTION
**Pull request by TonyCTHsu**
## Description

Provide system tests for Ruby lib injection.

## Workflow

1. ⚠️⚠️ Create your PR as draft (we're receiving lot of PR, it saves us lot of time) ⚠️⚠️
2. Follows the style guidelines of this project (See [how to easily lint the code](https://github.com/DataDog/system-tests/blob/main/docs/edit/lint.md))
3. Work on you PR until the CI passes (if something not related to your task is failing, you can ignore it)
4. Mark it as ready for review

> **_NOTE:_**  By default in PR only default scenario tests will be launched. Please refer to the [documentation](https://datadoghq.atlassian.net/wiki/spaces/APMINT/pages/2866381467/CI+Workflow+Github+Actions) to run all scenarios in your PR if needed.

Once your PR is reviewed, you can merge it ! :heart:

### CODE REVIEW

**Comment by GustavoCaso** [comment]
@TonyCTHsu Should we move the application to the ruby test apps? https://github.com/DataDog/system-tests-apps-ruby

We use that repo for all the appsec system tests. I think it would be nice to have all the ruby apps in a single location 😄

**Review by cbeauchesne — APPROVED** [review]

**Comment by TonyCTHsu** [comment]
@GustavoCaso I think it might make sense in the future. I want to place it under `ruby` for now because

1. It follows the convention that other languages of lib injection, that a sample app sits under its language namespace
2. The sample app is different from other in a peculiar way because it is not supposed to contain `ddtrace` in the bundled.

But overall, I would like to migrate to https://github.com/DataDog/system-tests-apps-ruby

**Comment by robertomonteromiguel** [comment]
> @GustavoCaso I think it might make sense in the future. I want to place it under `ruby` for now because
> 
> 1. It follows the convention that other languages of lib injection, that a sample app sits under its language namespace
> 2. The sample app is different from other in a peculiar way because it is not supposed to contain `ddtrace` in the bundled.
> 
> But overall, I would like to migrate to https://github.com/DataDog/system-tests-apps-ruby

Yest, I think  you should follow the convention that other languages of lib injection

**Comment by robertomonteromiguel** [comment]
> Can we add ruby to the test matrix
> 
> https://github.com/DataDog/system-tests/blob/0befccf0e662824f7735d0566445677bb7399365/.github/workflows/experimental.yml#L79
> 
> to validate that the tests work?

And the weblog variants....

**Review by robertomonteromiguel — CHANGES_REQUESTED** [review]
add weblog variants

**Comment by GustavoCaso** [comment]
@robertomonteromiguel I agree with the following conventions. It just feels weird that we have different conventions for different testing cases.

Still not a blocker at this point, but it would be nice to revisit it in the future 😄

**Pull request merged**
