### PR TITLE
lower library interface timeout for remote config tests

### PR DESCRIPTION
**Pull request by rochdev**
## Motivation

Waiting 100 seconds seems like a lot, especially since it should be possible to get the remote config from client libraries in milliseconds.

## Changes

Lower library interface timeout for remote config tests.

## Workflow

1. ⚠️ Create your PR as draft ⚠️
2. Work on you PR until the CI passes (if something not related to your task is failing, you can ignore it)
3. Mark it as ready for review
    * Test logic is modified? -> Get a review from RFC owner. We're working on refining the `codeowners` file quickly.
    * Framework is modified, or non obvious usage of it -> get a review from [R&P team](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X)

:rocket: Once your PR is reviewed, you can merge it!

🛟 [#apm-shared-testing](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X) 🛟

## Reviewer checklist

* [ ] If PR title starts with `[<language>]`, double-check that only `<language>` is impacted by the change
* [ ] No system-tests internal is modified. Otherwise, I have the approval from [R&P team](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X)
* [ ] CI is green, or failing jobs are not related to this change (and you are 100% sure about this statement)
* [ ] A docker base image is modified?
    * [ ] the relevant `build-XXX-image` label is present
* [ ] A scenario is added (or removed)?
    * [ ] Get a review from [R&P team](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X)

### CODE REVIEW

**Comment by rochdev** [comment]
I'm not sure what this is actually waiting for. It seems that waiting for 20s doesn't work with a poll interval of 2s, but it works with a polling interval of 1s, and the previous values were timeout of 100s with a polling interval of 5s. Does the timeout need to be 20x the polling interval? Is this checking for 20 remote config request? It's very unclear to me why it needs to wait for so long given that we can configure the polling interval all the way down to 1ms if needed.

cc @cbeauchesne

**Comment by rochdev** [comment]
Failures are on tests that are not affected by this change.

**Review by cbeauchesne — COMMENTED** [review]
Could you compute the time gain with the change of `DD_REMOTE_CONFIG_POLL_INTERVAL_SECONDS` ? 

Because it's far away from what we have in real condition, and the purpose of end-to-end is to be as close as possible from real conditions. We can deviate a little bit from this ideal line, but it must be worthy.

I've updated your branch to fix failures

**Review by cbeauchesne — COMMENTED** [review]
So far, the CI seems happy.

But I'd really like to know what is the gain of `DD_REMOTE_CONFIG_POLL_INTERVAL_SECONDS=0.25` before approving.

The change on `library_interface_timeout` is totally legit IMO.

**Comment by rochdev** [comment]
> Could you compute the time gain with the change of DD_REMOTE_CONFIG_POLL_INTERVAL_SECONDS ?

Time gain is pretty easy to calculate as it's literally the timeout, so it goes from 100 seconds to 5 seconds.

> the purpose of end-to-end is to be as close as possible from real conditions

It's still real condition, just faster. The fact that we're waiting 5 seconds every time in real environments is only so that we don't overload the backend, but in an isolated test there is no reason not to do this faster.

**Comment by cbeauchesne** [comment]
> Time gain is pretty easy to calculate as it's literally the timeout, so it goes from 100 seconds to 5 seconds.

I was speaking about `DD_REMOTE_CONFIG_POLL_INTERVAL_SECONDS`, not `library_interface_timeout`

**Comment by rochdev** [comment]
> I was speaking about DD_REMOTE_CONFIG_POLL_INTERVAL_SECONDS, not library_interface_timeout

Oh, well without lowering the poll interval, the remote config won't have been fetched before the timeout. As to why it needs to be ~20x lower than the timeout, I have no idea and the commit history was lost for that file so I don't know who could answer it. At the end of the day, the ratio is the same as before and everything is passing 🤷‍♂️

**Review by simon-id — APPROVED** [review]
LGTM but not I'm not part of system-tests core team

**Pull request merged**
