### PR TITLE
Mohammadislam/status error mapping test

### PR DESCRIPTION
**Pull request by chojomok**
## Description

* Added a new test for status error mapping 
* RFC: https://github.com/DataDog/architecture/blob/master/rfcs/apm/integrations/status-error-mapping/rfc.md
* The test checks to see if the server spans and client spans are marked as errors or not based on the environment variable  `DD_HTTP_SERVER_ERROR_STATUSES="500-510"` and `DD_HTTP_CLIENT_ERROR_STATUSES="400-413"`
* Currently only testing a case where a span should be an error and should not be an error, but will be updated if there are cases we find in support escalations in which another configuration should be tested as well.  

## Workflow

1. ⚠️⚠️ Create your PR as draft (we're receiving lot of PR, it saves us lot of time) ⚠️⚠️
2. Follows the style guidelines of this project (See [how to easily lint the code](https://github.com/DataDog/system-tests/blob/main/docs/edit/lint.md))
3. Work on you PR until the CI passes (if something not related to your task is failing, you can ignore it)
4. Mark it as ready for review

> **_NOTE:_**  By default in PR only default scenario tests will be launched. Please refer to the [documentation](https://datadoghq.atlassian.net/wiki/spaces/APMINT/pages/2866381467/CI+Workflow+Github+Actions) to run all scenarios in your PR if needed.

Once your PR is reviewed, you can merge it ! :heart:

### CODE REVIEW

**Comment by cbeauchesne** [comment]
Converting to draft as the CI is failing (I use the draft status tu save some time for PR reviews 😃 )

**Comment by cbeauchesne** [comment]
@chojomok gentle ping : do you still work on it, or can I close it ?

**Comment by cbeauchesne** [comment]
Gentle ping before closing @chojomok

**Review by cbeauchesne — COMMENTED** [review]
Still a draft, review being made when ready

**Comment by chojomok** [comment]
@cbeauchesne - so sorry, I don't check gh pings. slack is the best method to reach me.

**Pull request closed without merging**
