### PR TITLE
test(python): test body with application/xml format

### PR DESCRIPTION
**Pull request by juanjux**
Labelled as do-not-merge for now as it requires ddtrace-py 1.5.0.

Signed-off-by: Juanjo Alvarez <juanjo.alvarezmartinez@datadoghq.com>

### CODE REVIEW

**Comment by cbeauchesne** [comment]
Hi,

As version `1.5.0.rc1.dev` does not exists yet, even from last commit on the main branch of the tracer repo, the test is not executed. We must wait for it before merging this PR

**Comment by cbeauchesne** [comment]
Hi,

As version 1.5.0.rc1.dev does not exists yet, even from last commit on the main branch of the tracer repo, the test is not executed. We must wait for it before merging this PR

**Review by avara1986 — APPROVED** [review]

**Comment by cbeauchesne** [comment]
The dev version is still `1.4.0`, I change this PR to a draft (we receive daily notif on PR with missing review).

**Comment by juanjux** [comment]
Thanks @cbeauchesne, I will mark future PRs depending on unreleased versions as drafts to avoid this problem.

**Pull request closed without merging**
