### PR TITLE
Include prerelases in SemVer version comparator

### PR DESCRIPTION
**Pull request by simon-id**
## Motivation

We use prerelease versions in our master branch like `6.0.0-pre`. Those prerelease versions cannot be compared to the semver version definitions in the manifest, and thus put all tests as xpass instead of pass.

## Changes

Trim that "-pre" suffit, it's not important really.

## Workflow

1. ⚠️ Create your PR as draft ⚠️
2. Work on you PR until the CI passes (if something not related to your task is failing, you can ignore it)
3. Mark it as ready for review
    * Test logic is modified? -> Get a review from RFC owner. We're working on refining the `codeowners` file quickly.
    * Framework is modified, or non obvious usage of it -> get a review from [R&P team](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X)

:rocket: Once your PR is reviewed, you can merge it!

🛟 [#apm-shared-testing](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X) 🛟

## Reviewer checklist

* [ ] [Relevant label](https://github.com/DataDog/system-tests/blob/main/docs/CI/labels.md) (`run-parametric-scenario`, `run-profiling-scenario`...) are presents
* [ ] If PR title starts with `[<language>]`, double-check that only `<language>` is impacted by the change
* [ ] No system-tests internal is modified. Otherwise, I have the approval from [R&P team](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X)
* [ ] CI is green, or failing jobs are not related to this change (and you are 100% sure about this statement)
* [ ] A docker base image is modified?
    * [ ] the relevant `build-XXX-image` label is present
* [ ] A scenario is added (or removed)?
    * [ ] Get a review from [R&P team](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X)

### CODE REVIEW

**Review by robertomonteromiguel — CHANGES_REQUESTED** [review]
if you remove the version suffix, could the dev and prod have the same version?

**Comment by simon-id** [comment]
@robertomonteromiguel on master we always have a major above what we release, so for example latest is 5.x.x but on master we have 6.0.0-pre

**Review by uurien — APPROVED** [review]

**Comment by cbeauchesne** [comment]
> Those prerelease versions cannot be compared to the semver version definitions in the manifest

If I'm not wrong, in semver, `6.0.0-pre` will be after any `5.x.x` version, which is what we want, no ? Or do I miss something ?

**Comment by simon-id** [comment]
@cbeauchesne
> 6.0.0-pre will be after any 5.x.x version

From what I can tell the spec is not super clear on it, but npm and the python library used in the system-tests do not agree with you, this is what i'm trying to solve. Basically without this fix, all the test from dev are xpass because 6.0.0-pre is considered not satisfying the >=5 filter

See:
image
image

**Review by robertomonteromiguel — APPROVED** [review]

**Comment by simon-id** [comment]
I'm trying to fix it for node for now, we'll see if it impacts other libs when they start using it

**Comment by simon-id** [comment]
I think the reason why they differ is because the `NpmSpec` is mimic'ing the [npm semver module](https://www.npmjs.com/package/semver). Here is a quote from its docs:
image
So a prerelease version will only match if compared to another prerelase version.
@cbeauchesne The problem with the `SimpleSpec`, is that it's actually too simple. It doesn't look like it supports OR clauses like the npmspec do, and that's like the whole reason why we're using it in the first place.

**Comment by cbeauchesne** [comment]
indeed. 

let's go with a custom one !

**Review by cbeauchesne — APPROVED** [review]

**Comment by simon-id** [comment]
LGTM thank you so much, way better solution, and i confirmed it works great locally :+1:

**Pull request merged**
