### PR TITLE
Fix warnings in lib-injection 

### PR DESCRIPTION
**Pull request by cbeauchesne**
## Motivation

Clean CI !

## Changes

Fix warnings in lib-injection 

image

## Workflow

1. ⚠️ Create your PR as draft ⚠️
2. Work on you PR until the CI passes (if something not related to your task is failing, you can ignore it)
3. Mark it as ready for review
    * Test logic is modified? -> Get a review from RFC owner. We're working on refining the `codeowners` file quickly.
    * Framework is modified, or non obvious usage of it -> get a review from [R&P team](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X)

:rocket: Once your PR is reviewed, you can merge it!

🛟 [#apm-shared-testing](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X) 🛟

## Reviewer checklist

* [ ] [Relevant label](https://github.com/DataDog/system-tests/blob/main/docs/CI/labels.md) (`run-parametric-scenario`, `run-profiling-scenario`...) are presents
* [ ] If PR title starts with `[<language>]`, double-check that only `<language>` is impacted by the change
* [ ] No system-tests internal is modified. Otherwise, I have the approval from [R&P team](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X)
* [ ] CI is green, or failing jobs are not related to this change (and you are 100% sure about this statement)
* [ ] A docker base image is modified?
    * [ ] the relevant `build-XXX-image` label is present
* [ ] A scenario is added (or removed)?
    * [ ] Get a review from [R&P team](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X)

### CODE REVIEW

**Review by robertomonteromiguel — CHANGES_REQUESTED** [review]
Some months ago the dotnet people found a bug on the buildx tool.
With the latest version of the tool we were pushing to GHCR imagenes with the platform "unkonw".
I had prepared a PR like yours but I noticed of this problem before merged and I have never merged.

**Comment by cbeauchesne** [comment]
This error should pop in the CI? because so far, it's very very green 🟢

**Comment by robertomonteromiguel** [comment]
> This error should pop in the CI? because so far, it's very very green 🟢

Problems could arise if we publish images to the ghcr registry.

**Comment by robertomonteromiguel** [comment]
yes, let's try. I'm going to add label to generate buddies, and label to generate lib injection images.
Also I'm going to add labels to run integrations and lib injection tests.
Let's check the results to make a decission....

**Comment by cbeauchesne** [comment]
python failures : #2402

**Pull request merged**
