### PR TITLE
User blocking

### PR DESCRIPTION
**Pull request by cataphract**
## Description

Implement test for user blocking.

## Check list

Your PR is not ready to be reviewed? Please save it as a draft :pray:

- [ ] Follows the style guidelines of this project (See [how to easily lint the code](https://github.com/DataDog/system-tests/blob/main/docs/edit/lint.md))
- [ ] CI is passing
- [ ] There is at least one approval from code owners

Yes to all? Feel free to merge it whenever you want :heart:

### CODE REVIEW

**Comment by smola** [comment]
Anything we need to port to https://github.com/DataDog/system-tests/pull/860 ?

**Comment by cbeauchesne** [comment]
Hi @cataphract ,

Is this PR still relevant ? or can I close it ?

**Comment by cataphract** [comment]
> Hi @cataphract ,
> 
> Is this PR still relevant ? or can I close it ?

Yes, still relevant.

**Comment by cataphract** [comment]
Still needs https://github.com/DataDog/dd-trace-java/pull/5275

**Comment by cbeauchesne** [comment]
@cataphract  https://github.com/DataDog/dd-trace-java/pull/5275 and https://github.com/DataDog/dd-trace-java/pull/5353 are merged, is this PR still relevant ?

**Comment by cbeauchesne** [comment]
@cataphract gentle ping 😃

**Comment by cbeauchesne** [comment]
Seen with @smola , we can close this PR. See APPSEC-51385

**Pull request closed without merging**
